# Site settings
title: Padaria Morumbi
email: maciel.bombonato@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.padariamorumbi.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: null #pygments
lsi: false
safe: false
